### ISSUE TITLE
Broken link push.js

### ISSUE THREAD

**Issue by TixieBorg** [GlitchFamily/vanillalist#18]
http://nickersoft.github.io/push.js/demo.html

**Comment by NaincyKumariKnoldus** [comment]
Hey @TixieBorg Can I do this? Can you please provide me the correct link for this.

**Comment by TixieBorg** [comment]
@NaincyKumariKnoldus I get that covered but thank you for your proposition

**Comment by TixieBorg** [comment]
Unmaintained, to remove

**Comment by TixieBorg** [comment]
Removed with https://github.com/GlitchFamily/vanillalist/commit/9753fe237134f392f9ed49c4a90fd563cf39cd96
